import * as fs from "node:fs";
import * as path from "node:path";
import * as vscode from "vscode";

interface LockEntry {
  template: string;
  parameters: Record<string, string | boolean | number>;
  files: Array<{ output: string; template_path: string }>;
  generated_at: string;
}

interface LokioLock {
  generations: LockEntry[];
}

function loadLock(root: string): LokioLock | null {
  const lockPath = path.join(root, "lokio.lock");
  if (!fs.existsSync(lockPath)) return null;
  try {
    // biome-ignore: dynamic require
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const yaml = require("js-yaml") as typeof import("js-yaml");
    return yaml.load(fs.readFileSync(lockPath, "utf-8")) as LokioLock;
  } catch {
    return null;
  }
}

export class LokioCodeLensProvider implements vscode.CodeLensProvider {
  private _onDidChangeCodeLenses = new vscode.EventEmitter<void>();
  readonly onDidChangeCodeLenses = this._onDidChangeCodeLenses.event;

  refresh(): void {
    this._onDidChangeCodeLenses.fire();
  }

  provideCodeLenses(
    document: vscode.TextDocument,
  ): vscode.CodeLens[] | undefined {
    const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
    if (!root) return;

    const lock = loadLock(root);
    if (!lock?.generations) return;

    const relPath = path.relative(root, document.uri.fsPath).replace(/\\/g, "/");
    const lenses: vscode.CodeLens[] = [];

    for (const entry of lock.generations) {
      const match = entry.files.find((f) => f.output === relPath);
      if (!match) continue;

      const range = new vscode.Range(0, 0, 0, 0);
      const generated = new Date(entry.generated_at).toLocaleDateString();

      // "Generated by Lokio" lens
      lenses.push(
        new vscode.CodeLens(range, {
          title: `$(package) Generated by Lokio · ${entry.template}`,
          command: "",
          tooltip: `Template: ${match.template_path}\nGenerated: ${generated}`,
        }),
      );

      // "Sync" lens
      lenses.push(
        new vscode.CodeLens(range, {
          title: "$(sync) Sync",
          command: "lokio.syncFile",
          arguments: [document.uri.fsPath],
          tooltip: "Re-generate this file with 3-way merge (preserves your edits)",
        }),
      );

      // Show params as lens
      const paramStr = Object.entries(entry.parameters)
        .map(([k, v]) => `${k}=${v}`)
        .join(", ");
      if (paramStr) {
        lenses.push(
          new vscode.CodeLens(range, {
            title: `$(symbol-field) ${paramStr}`,
            command: "",
            tooltip: "Parameters used to generate this file",
          }),
        );
      }
    }

    return lenses;
  }
}
